// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2z1c-Uiv50qxPZOwKuqh1VG87KzmlkNw',
    appId: '1:180944097442:web:cb6244d800e306cee407fb',
    messagingSenderId: '180944097442',
    projectId: 'dairy-harbor-mobile',
    authDomain: 'dairy-harbor-mobile.firebaseapp.com',
    storageBucket: 'dairy-harbor-mobile.appspot.com',
    measurementId: 'G-HQB2HLWKV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABxoAiXruglakT_sz-cn8yBFYOyR86Q-s',
    appId: '1:180944097442:android:5444a9ec0636b3c7e407fb',
    messagingSenderId: '180944097442',
    projectId: 'dairy-harbor-mobile',
    storageBucket: 'dairy-harbor-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWpf6cpwKtRdrBSiCEbvKMqYvIZXRqmA',
    appId: '1:180944097442:ios:333e40231e8d8eb1e407fb',
    messagingSenderId: '180944097442',
    projectId: 'dairy-harbor-mobile',
    storageBucket: 'dairy-harbor-mobile.appspot.com',
    iosBundleId: 'com.example.dairyHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWpf6cpwKtRdrBSiCEbvKMqYvIZXRqmA',
    appId: '1:180944097442:ios:333e40231e8d8eb1e407fb',
    messagingSenderId: '180944097442',
    projectId: 'dairy-harbor-mobile',
    storageBucket: 'dairy-harbor-mobile.appspot.com',
    iosBundleId: 'com.example.dairyHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2z1c-Uiv50qxPZOwKuqh1VG87KzmlkNw',
    appId: '1:180944097442:web:ea9b99d3d8fc9a8ce407fb',
    messagingSenderId: '180944097442',
    projectId: 'dairy-harbor-mobile',
    authDomain: 'dairy-harbor-mobile.firebaseapp.com',
    storageBucket: 'dairy-harbor-mobile.appspot.com',
    measurementId: 'G-5NPCQT8BNY',
  );

}