// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5k2qKMrKfH0b1G4ZPginJx4J8y3iKTDo',
    appId: '1:338147366713:web:2710eb0627893d142bbae8',
    messagingSenderId: '338147366713',
    projectId: 'scupay-aa2ee',
    authDomain: 'scupay-aa2ee.firebaseapp.com',
    databaseURL: 'https://scupay-aa2ee-default-rtdb.firebaseio.com',
    storageBucket: 'scupay-aa2ee.appspot.com',
    measurementId: 'G-HP1K8M1K7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArt-GnJOM-2SHgwO12GyQPxRYX3mURIvc',
    appId: '1:338147366713:android:e69bc7b7888b34c72bbae8',
    messagingSenderId: '338147366713',
    projectId: 'scupay-aa2ee',
    databaseURL: 'https://scupay-aa2ee-default-rtdb.firebaseio.com',
    storageBucket: 'scupay-aa2ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFCRU4swOfriCx2zZvRZYSFWBaUCAfJw',
    appId: '1:338147366713:ios:10b5e7f0f81ac77e2bbae8',
    messagingSenderId: '338147366713',
    projectId: 'scupay-aa2ee',
    databaseURL: 'https://scupay-aa2ee-default-rtdb.firebaseio.com',
    storageBucket: 'scupay-aa2ee.appspot.com',
    iosBundleId: 'com.example.dairyHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFCRU4swOfriCx2zZvRZYSFWBaUCAfJw',
    appId: '1:338147366713:ios:10b5e7f0f81ac77e2bbae8',
    messagingSenderId: '338147366713',
    projectId: 'scupay-aa2ee',
    databaseURL: 'https://scupay-aa2ee-default-rtdb.firebaseio.com',
    storageBucket: 'scupay-aa2ee.appspot.com',
    iosBundleId: 'com.example.dairyHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5k2qKMrKfH0b1G4ZPginJx4J8y3iKTDo',
    appId: '1:338147366713:web:97b6c127fe3661502bbae8',
    messagingSenderId: '338147366713',
    projectId: 'scupay-aa2ee',
    authDomain: 'scupay-aa2ee.firebaseapp.com',
    databaseURL: 'https://scupay-aa2ee-default-rtdb.firebaseio.com',
    storageBucket: 'scupay-aa2ee.appspot.com',
    measurementId: 'G-E18H2EJ40W',
  );
}
